#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d I II III IV V VI VII 
bspc monitor HDMI-1 -d VIII IX X

bspc config border_radius		    3
bspc config border_width         	    3
bspc config window_gap          	    10
bspc config click_to_focus		    true
bspc config focus_follows_pointer	    true

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focused_border_color      '#7b05b5'
bspc config urgent_border_color       '#dd2727'

bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^9' follow=on focus=on
bspc rule -a discord desktop='^2' follow=on
bspc rule -a spotify desktop='^3' follow=on
bspc rule -a thunderbird desktop='^2' follow=on
bspc rule -a KeePassXC state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a qbittorrent desktop="^3"
bspc rule -a hexchat desktop="^2"

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

${HOME}/.config/.fehbg
xrandr --output DP-1 --primary --set TearFree on
xrandr --output HDMI-1 --rotate right
xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh
picom --no-vsync --no-use-damage
