#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X

bspc config border_radius		         	4
bspc config border_width         	    2
bspc config window_gap          	    10
bspc config click_to_focus			      true
bspc config focus_follows_pointer	    true

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focused_border_color      '#7b05b5'
bspc config urgent_border_color       '#dd2727'


bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^4' follow=on focus=on
bspc rule -a discord desktop='^2' follow=on
bspc rule -a spotify desktop='^2' follow=on
bspc rule -a Thunderbird desktop='^5' follow=on
bspc rule -a KeePassXC desktop='^1' state=floating
bspc rule -a Org.gnome.Nautilus state=floating

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

${HOME}/.config/.fehbg
xrandr --output DP-1 --primary
xrandr --output HDMI-1 --rotate right
xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh &
